title: C'MUNK
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: Design | Entertainment | Marketing
color:
  saturation: 1
  brandStrength: 0.9719235
  lightness: 1
  brandColors:
    - '#393738'
    - '#C8D2DE'
    - '#6E706F'
    - '#BC4B5B'
    - '#FFB804'
  rhythmicContrast: 0.5454002
cta:
  bucket: null
  version: null
  domain: null
name: C'MUNK
author:
  name: Chip Houghton
  email: ''
favicon: null
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: null
  facebook: null
typography_spectrum: 0.6123058
layout_spectrum: 0.2025089
