title: "C'MUNK: DIGITAL FORCES"
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8797531
  brandStrength: 0.1875
  lightness: 0.6827956
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  rhythmicContrast: 0.75
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: "C'MUNK"
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5063265454955399
layout_spectrum: 0.5941895546857268
