title: 'C''MUNK: DIGITAL FORCES'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8797531
  brandStrength: 0.1391876
  lightness: 0.6827956
  brandColors:
    - '#FF783C'
    - '#1A1500'
    - '#CB3E01'
    - '#88714F'
    - '#FFDD7A'
  rhythmicContrast: 0.75
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: C'MUNK
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5063265454955399
layout_spectrum: 0.3052569
